import type { AuditReport, Finding, Severity, Status } from '../types.js';
import type { MaturityProfile } from '../engine/maturity.js';

const TAG: Record<Status, string> = {
  PASS: '✅',
  FAIL: '🔴',
  WRONG: '⚠️',
  MISSING: '🚫',
  DEPRECATED: '💀',
  EXPERIMENTAL: '🧪',
  UNKNOWN: '❓',
  NOT_APPLICABLE: '➖',
};

const SEV_TAG: Record<Severity, string> = {
  CRITICAL: '🔴',
  HIGH: '🟠',
  MEDIUM: '🟡',
  LOW: '🟢',
  FUTURE: '🔵',
};

const SEV_NAME: Record<Severity, string> = {
  CRITICAL: 'CRITICAL',
  HIGH: 'HIGH',
  MEDIUM: 'MEDIUM',
  LOW: 'LOW',
  FUTURE: 'FUTURE',
};

const STATUS_NAME: Record<Status, string> = {
  PASS: 'GOOD',
  FAIL: 'FAIL',
  WRONG: 'WRONG',
  MISSING: 'MISSING',
  DEPRECATED: 'DEPRECATED',
  EXPERIMENTAL: 'EXPERIMENTAL',
  UNKNOWN: 'NEEDS REVIEW',
  NOT_APPLICABLE: 'SKIPPED',
};

type Print = (line?: string) => void;

/** Renders the Section 14 report template from USA.md. */
export function renderMarkdown(report: AuditReport, profile: MaturityProfile): string {
  const out: string[] = [];
  const p: Print = (line = '') => out.push(line);

  const findings = report.findings;
  const active = findings.filter((f) => !f.suppressedReason);
  const suppressed = findings.filter((f) => Boolean(f.suppressedReason));
  const unresolved = active.filter((f) => f.status === 'UNKNOWN');
  const actioned = active.filter((f) => f.status !== 'PASS' && f.status !== 'UNKNOWN');
  const passed = active.filter((f) => f.status === 'PASS');

  renderReportHeader(p, report, profile);
  renderExecutiveSummary(p, report, profile);
  renderCounts(p, report, suppressed.length);
  renderImmediate(p, actioned);
  renderBySection(p, report, profile, actioned, passed);
  renderJudgementQueue(p, unresolved);
  renderSuppressed(p, suppressed);
  renderRoadmap(p, profile, actioned);
  renderAppendix(p, report);
  renderTrailerBlock(p, report);

  return out.join('\n');
}

/* --------------------------------------------------------------- header -- */

function renderReportHeader(p: Print, report: AuditReport, profile: MaturityProfile): void {
  p('# 🔍 Universal Software Audit Report');
  p();
  p(`> Generated by **USA** · schema \`${report.schema}\``);
  p();
  p('| | |');
  p('|---|---|');
  p(`| **Project** | \`${report.target.name}\` |`);
  p(`| **Path** | \`${report.target.path}\` |`);
  if (report.target.repoUrl) p(`| **Repository** | ${report.target.repoUrl} |`);
  p(
    `| **Commit** | ${report.target.commit ? `\`${report.target.commit.slice(0, 8)}\`` : 'n/a'} (${report.target.ref ?? 'detached'}) |`,
  );
  p(`| **Date** | ${report.generatedAt} |`);
  p(`| **USA version** | ${report.usaVersion} |`);
  p(`| **Detected type** | ${humanList(report.detection.projectTypes) || 'unclassified'} |`);
  p(`| **Platform** | ${humanList(report.detection.platforms) || 'unclassified'} |`);
  p(
    `| **Stack** | ${humanList([...report.detection.languages, ...report.detection.frameworks])} |`,
  );
  p(
    `| **Maturity** | ${profile.label}${report.options.profile === 'auto' ? ' *(auto-detected)*' : ' *(forced)*'} |`,
  );
  p(`| **Depth** | ${report.options.depth} |`);
  p();
}

/* -------------------------------------------------------------- summary -- */

function renderExecutiveSummary(p: Print, report: AuditReport, profile: MaturityProfile): void {
  p('## 📊 Executive Summary');
  p();
  const band = report.score.expectedBand;
  const coverage = report.score.automationCoverage;
  const queue = report.score.counts.UNKNOWN ?? 0;
  p(`### Overall Health Score: **${report.score.overall}/100**`);
  p();
  p(`${bar(report.score.overall, 100)}`);
  p();
  p(
    `Verified automatically: **${fmt(coverage)}%** of applicable checks. ` +
      `${queue} check${queue === 1 ? '' : 's'} need a human — see the judgement queue.`,
  );
  p();
  if (coverage < 60) {
    p(
      `> ⚠️ **Read this score as a floor, not a grade.** Only ${fmt(coverage)}% of applicable ` +
        `checks could be resolved without a human. The unverified ${100 - Math.round(coverage)}% ` +
        `is not "passing" — it is unknown, and it is excluded from the arithmetic above rather ` +
        `than counted as credit.`,
    );
    p();
  }
  p(
    `Expected band for **${profile.label}**: ${band[0]}–${band[1]} — ${verdict(report.score.overall, band)}`,
  );
  p();
  if (profile.summary) p(`> ${profile.summary.trim()}`);
  p();

  p('| Dimension | Score | Confidence |');
  p('|---|---|---|');
  for (const s of report.score.sections) {
    p(renderSectionRow(s));
  }
  p();
  p(
    `*Confidence = share of applicable rules the engine could verify automatically; ` +
      `unverified checks are excluded from the score rather than counted as passes. ` +
      `**†** = fewer than half of that section's applicable checks could be verified. ` +
      `Automation coverage: **${fmt(coverage)}%**. The rest is in the judgement queue below.*`,
  );
  p();
}

function renderSectionRow(s: {
  id: string;
  title: string;
  score: number | null;
  confidence: number;
}): string {
  // A section can score 10/10 on one verified rule out of six. Mark it, so a
  // perfect-looking table does not imply a thorough audit.
  const thin = s.score !== null && s.confidence < 50 ? ' †' : '';
  return s.score === null
    ? `| ${s.id} · ${s.title} | — not verified | 0% |`
    : `| ${s.id} · ${s.title} | ${fmt(s.score)}/10${thin} | ${fmt(s.confidence)}% |`;
}

/* --------------------------------------------------------------- counts -- */

function countsRow(statusPart: string, severityPart: string): string {
  return `| ${statusPart} : | ${severityPart}`;
}

function renderCounts(p: Print, report: AuditReport, suppressedCount: number): void {
  p('## 🏷️ Findings Summary');
  p();
  p('| Status | Count | | Severity (open findings) | Count |');
  p('|---|--:|-|---|--:|');
  const statusRows: Status[] = [
    'PASS',
    'FAIL',
    'WRONG',
    'MISSING',
    'DEPRECATED',
    'EXPERIMENTAL',
    'UNKNOWN',
  ];
  const sevRows: Severity[] = ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'FUTURE'];
  for (let i = 0; i < Math.max(statusRows.length, sevRows.length); i++) {
    p(countsRow(statusCell(report, statusRows[i]), severityCell(report, sevRows[i])));
  }
  p();
  if (suppressedCount > 0) {
    p(
      `*${suppressedCount} finding(s) suppressed by project policy — see [Accepted risk](#-accepted-risk-suppressions).*`,
    );
    p();
  }
}

function statusCell(report: AuditReport, st: Status | undefined): string {
  if (!st) return '  |  |';
  return `${TAG[st]} ${STATUS_NAME[st]} | ${report.score.counts[st] ?? 0} |`;
}

function severityCell(report: AuditReport, sv: Severity | undefined): string {
  if (!sv) return '  |  |';
  return `${SEV_TAG[sv]} ${SEV_NAME[sv]} | ${report.score.severityCounts[sv] ?? 0} |`;
}

/* ------------------------------------------------------------- immediate -- */

function renderImmediate(p: Print, actioned: Finding[]): void {
  p('## 🚨 Immediate Action Required');
  p();
  const urgent = actioned
    .filter((f) => f.severity === 'CRITICAL' || f.severity === 'HIGH')
    .slice(0, 15);
  if (urgent.length === 0) {
    p('No CRITICAL or HIGH findings. Nice.');
    p();
    return;
  }
  urgent.forEach((f, i) => renderUrgentItem(p, f, i));
  p();
}

function renderUrgentItem(p: Print, f: Finding, i: number): void {
  const loc = primaryLocation(f);
  p(`${i + 1}. ${SEV_TAG[f.severity]} **${f.title}** · \`${f.ruleId}\``);
  p(`   - **Where:** ${loc}`);
  p(`   - **Why:** ${f.message}`);
  if (f.remediation) p(`   - **Fix:** ${f.remediation}`);
}

/* ------------------------------------------------------------ by section -- */

function renderBySection(
  p: Print,
  report: AuditReport,
  profile: MaturityProfile,
  actioned: Finding[],
  passed: Finding[],
): void {
  p('## 📁 Section-by-Section Findings');
  p();
  const sectionMeta = new Map(report.score.sections.map((s) => [s.id, s]));
  const bySection = groupBy(actioned, (f) => f.section);
  const sectionIds = [...new Set([...report.score.sections.map((s) => s.id), ...bySection.keys()])];
  sectionIds.sort((a, b) => a.localeCompare(b, undefined, { numeric: true }));

  for (const id of sectionIds) {
    renderSectionBlock(p, profile, id, sectionMeta.get(id), bySection.get(id) ?? [], passed);
  }
}

function renderSectionBlock(
  p: Print,
  profile: MaturityProfile,
  id: string,
  meta:
    | {
        title: string;
        score: number | null;
        applicable: number;
        passed: number;
        failed: number;
        unknown: number;
      }
    | undefined,
  items: Finding[],
  passed: Finding[],
): void {
  const good = passed.filter((f) => f.section === id);
  const title = meta?.title ?? items[0]?.sectionTitle ?? id;
  p(`### ${id} · ${title}`);
  p();
  if (meta) {
    p(sectionScoreLine(meta));
    p();
  }
  if (items.length === 0) {
    p('No open findings in this section. ✅');
    p();
    return;
  }
  for (const f of items.sort(severityOrder)) {
    renderSectionFinding(p, f, profile.label);
  }
  renderPassingDetails(p, id, good);
  p();
}

function sectionScoreLine(meta: {
  score: number | null;
  applicable: number;
  passed: number;
  failed: number;
  unknown: number;
}): string {
  return meta.score === null
    ? `**Not automatically verifiable** · ` +
        `${meta.applicable} applicable rule(s), all requiring judgement.`
    : `**Score ${fmt(meta.score)}/10** · ${bar(meta.score, 10)} · ` +
        `${meta.passed} passed / ${meta.failed} open / ${meta.unknown} to review`;
}

function renderSectionFinding(p: Print, f: Finding, profileLabel: string): void {
  p(`- ${TAG[f.status]} **${f.title}** \`${f.ruleId}\` — ${f.message}`);
  if (f.locations.length > 0) {
    p(
      `  - 📍 ${f.locations.slice(0, 4).map(fmtLocation).join(', ')}${f.locations.length > 4 ? ` (+${f.locations.length - 4})` : ''}`,
    );
  }
  if (f.dampened) {
    p(`  - 🪶 Downgraded ${f.baseSeverity} → ${f.severity} by the ${profileLabel} profile`);
  }
  if (f.remediation) p(`  - 🛠️ ${f.remediation}`);
  if (f.references?.length) p(`  - 📚 ${f.references.join(' · ')}`);
}

function renderPassingDetails(p: Print, id: string, good: Finding[]): void {
  if (good.length === 0) return;
  p();
  p(`<details><summary>${good.length} check(s) passing in ${id}</summary>`);
  p();
  for (const f of good) p(`- ✅ ${f.title} \`${f.ruleId}\``);
  p();
  p('</details>');
}

/* ------------------------------------------------------------- judgement -- */

function renderJudgementQueue(p: Print, unresolved: Finding[]): void {
  p('## 🧠 Judgement Queue (agent / human review)');
  p();
  p('These checks cannot be settled by grep. Work through them with an agent or a reviewer;');
  p('each one records the evidence required. **RULE 4: never mark ✅ without evidence.**');
  p();
  if (unresolved.length === 0) {
    p('Nothing pending — every applicable rule was resolved automatically.');
    p();
    return;
  }
  p('| Rule | Section | Severity | What to look for | Evidence to record |');
  p('|---|---|---|---|---|');
  for (const f of unresolved) {
    p(
      `| \`${f.ruleId}\` ${escapeCell(f.title)} | ${f.section} | ${SEV_TAG[f.severity]} ${f.severity} | ` +
        `${escapeCell(f.why ?? f.message)} | ${escapeCell(f.evidenceHint ?? 'file:line + reasoning')} |`,
    );
  }
  p();
}

/* ------------------------------------------------------------ suppressed -- */

function renderSuppressed(p: Print, suppressed: Finding[]): void {
  if (suppressed.length === 0) return;
  p('## 🤝 Accepted Risk (suppressions)');
  p();
  // Site-level waivers point at a place; show it so an accepted risk is
  // reviewable at the exact location, not just the rule (ADR-0022).
  const anyLocated = suppressed.some((f) => f.locations.length > 0);
  if (anyLocated) {
    p('| Rule | Severity | Where | Reason |');
    p('|---|---|---|---|');
    for (const f of suppressed) {
      p(
        `| \`${f.ruleId}\` ${escapeCell(f.title)} | ${SEV_TAG[f.severity]} ${f.severity} | ${escapeCell(locationLabel(f))} | ${escapeCell(f.suppressedReason ?? '')} |`,
      );
    }
  } else {
    p('| Rule | Severity | Reason |');
    p('|---|---|---|');
    for (const f of suppressed) {
      p(
        `| \`${f.ruleId}\` ${escapeCell(f.title)} | ${SEV_TAG[f.severity]} ${f.severity} | ${escapeCell(f.suppressedReason ?? '')} |`,
      );
    }
  }
  p();
}

/** `file:line` for the first location, or `—` when the finding has none. */
function locationLabel(f: Finding): string {
  const loc = f.locations[0];
  if (!loc) return '—';
  return loc.line === undefined ? loc.file : `${loc.file}:${loc.line}`;
}

/* --------------------------------------------------------------- roadmap -- */

function renderRoadmap(p: Print, profile: MaturityProfile, actioned: Finding[]): void {
  p('## 🗺️ Recommended Roadmap');
  p();
  const sprint0 = actioned.filter(
    (f) => f.severity === 'CRITICAL' || (f.severity === 'HIGH' && f.ruleClass === 'security'),
  );
  const sprint1 = actioned.filter(
    (f) => f.severity === 'HIGH' && !(f.severity === 'HIGH' && f.ruleClass === 'security'),
  );
  roadmapBlock(p, 'SPRINT 0 · now', 'Stop the bleeding. Ship before anything else.', sprint0);
  roadmapBlock(p, 'SPRINT 1 · next 1–2 weeks', 'Close the remaining HIGH-severity debt.', sprint1);
  roadmapBlock(
    p,
    'SPRINT 2 · next month',
    'MEDIUM gaps — schedule them or they never happen.',
    actioned.filter((f) => f.severity === 'MEDIUM'),
  );
  roadmapBlock(
    p,
    'BACKLOG',
    'LOW and FUTURE items. Re-read after the next audit.',
    actioned.filter((f) => f.severity === 'LOW' || f.severity === 'FUTURE'),
  );

  if (profile.focus.length > 0) {
    p(`### 🎯 What actually matters at **${profile.label}**`);
    p();
    for (const f of profile.focus) p(`- ${f}`);
    p();
  }
  if (profile.defer.length > 0) {
    p('<details><summary>Deliberately deferred at this stage</summary>');
    p();
    for (const d of profile.defer) p(`- ~~${d}~~`);
    p();
    p('</details>');
    p();
  }
}

/* -------------------------------------------------------------- appendix -- */

function renderAppendix(p: Print, report: AuditReport): void {
  p('## 🧾 Appendix');
  p();
  p('<details><summary>Detection facts</summary>');
  p();
  p('```yaml');
  p(`maturity: ${report.detection.maturity}`);
  p(`languages: [${report.detection.languages.join(', ')}]`);
  p(`frameworks: [${report.detection.frameworks.join(', ')}]`);
  p(`package_managers: [${report.detection.packageManagers.join(', ')}]`);
  p(`databases: [${report.detection.databases.join(', ')}]`);
  p(`platforms: [${report.detection.platforms.join(', ')}]`);
  p(`flags: [${report.detection.flags.join(', ')}]`);
  p('metrics:');
  for (const [k, v] of Object.entries(report.detection.metrics)) p(`  ${k}: ${v}`);
  p('```');
  p();
  p('Maturity signals:');
  p();
  for (const s of report.detection.maturitySignals) p(`- ${s}`);
  p();
  p(
    `Rule packs loaded (${report.options.packsLoaded.length}): ${report.options.packsLoaded.join(', ') || 'none'}`,
  );
  p();
  p(
    `Rule packs skipped as not applicable (${report.options.packsSkipped.length}): ${report.options.packsSkipped.join(', ') || 'none'}`,
  );
  p();
  p('</details>');
  p();
  p('---');
  p();
  p(
    '<sub>Report generated by USA — the Universal Software Auditor. ' +
      'Scores are reproducible: re-run with the same rules and depth to compare. ' +
      'USA checks process and code hygiene; it is not a penetration test.</sub>',
  );
  p();
}

/* --------------------------------------------------------------- trailer -- */

function renderTrailerBlock(p: Print, report: AuditReport): void {
  p(TRAILER_BEGIN);
  p('```yaml');
  p(trailer(report));
  p('```');
  p(TRAILER_END);
  p();
}

/* --------------------------------------------------------------- helpers -- */

function roadmapBlock(
  p: (s?: string) => void,
  title: string,
  blurb: string,
  items: Finding[],
): void {
  p(`### ${title}`);
  p();
  p(`*${blurb}*`);
  p();
  if (items.length === 0) {
    p('Nothing here. ✅');
    p();
    return;
  }
  for (const f of [...items].sort(severityOrder).slice(0, 25)) {
    p(
      `- ${SEV_TAG[f.severity]} \`${f.ruleId}\` ${f.title}${f.remediation ? ` → ${f.remediation}` : ''}`,
    );
  }
  if (items.length > 25) p(`- …and ${items.length - 25} more`);
  p();
}

function severityOrder(a: Finding, b: Finding): number {
  const o: Record<string, number> = { CRITICAL: 0, HIGH: 1, MEDIUM: 2, LOW: 3, FUTURE: 4 };
  return (o[a.severity] ?? 9) - (o[b.severity] ?? 9);
}

export function primaryLocation(f: Finding): string {
  if (f.locations.length === 0) return 'project-wide';
  return f.locations.slice(0, 3).map(fmtLocation).join(', ');
}

function fmtLocation(l: { file: string; line?: number }): string {
  return `\`${l.file}${typeof l.line === 'number' ? `:${l.line}` : ''}\``;
}

function fmt(n: number): string {
  return Number.isInteger(n) ? String(n) : n.toFixed(1);
}

function bar(value: number, max: number, width = 24): string {
  const filled = Math.max(0, Math.min(width, Math.round((value / max) * width)));
  return `\`${'█'.repeat(filled)}${'░'.repeat(width - filled)}\``;
}

function verdict(score: number, band: [number, number]): string {
  if (score >= band[1]) return '**above the expected band** 🎉';
  if (score >= band[0]) return '**within the expected band** 👍';
  if (score >= band[0] - 15) return '**just below the expected band** — close the HIGH findings';
  return '**well below the expected band** — start with SPRINT 0';
}

function humanList(items: string[]): string {
  const uniq = [...new Set(items)];
  if (uniq.length === 0) return '';
  if (uniq.length <= 4) return uniq.join(', ');
  return `${uniq.slice(0, 4).join(', ')} +${uniq.length - 4}`;
}

function groupBy<T>(items: T[], key: (t: T) => string): Map<string, T[]> {
  const m = new Map<string, T[]>();
  for (const item of items) {
    const k = key(item);
    const list = m.get(k) ?? [];
    list.push(item);
    m.set(k, list);
  }
  return m;
}

function escapeCell(s: string): string {
  // Backslashes first: escaping `|` without escaping `\` lets an input
  // backslash turn into an escape for the character that follows it.
  return s.replace(/\\/g, '\\\\').replace(/\|/g, '\\|').replace(/\n/g, ' ').trim();
}

/**
 * Compact, stable YAML used by `usa diff`. Kept in the Markdown on purpose —
 * the report stays a single self-contained artifact you can commit, email, or
 * paste into a PR.
 */
export const TRAILER_BEGIN = '<!-- USA:TRAILER:BEGIN -->';
export const TRAILER_END = '<!-- USA:TRAILER:END -->';

export function trailer(report: AuditReport): string {
  const lines: string[] = [];
  lines.push('schema: usa-report-v1');
  lines.push(`generated_at: ${report.generatedAt}`);
  lines.push(`usa_version: ${report.usaVersion}`);
  lines.push(`overall: ${report.score.overall}`);
  lines.push('sections:');
  for (const s of report.score.sections) {
    lines.push(`  ${s.id}: {score: ${s.score}, open: ${s.failed}, review: ${s.unknown}}`);
  }
  lines.push('severity_totals:');
  for (const [k, v] of Object.entries(report.score.severityCounts)) {
    lines.push(`  ${k}: ${v}`);
  }
  lines.push('rules:');
  for (const f of report.findings) {
    lines.push(
      `  ${yamlKey(f.ruleId)}: {status: ${f.status}, severity: ${f.severity}, section: ${f.section}}`,
    );
  }
  return lines.join('\n');
}

/**
 * Rule IDs are pack-author-controlled input to a machine-parsed channel.
 * An unquoted id containing `:`, `#`, a newline, or a ``` fence truncates
 * or corrupts the YAML mapping the trailer — and therefore `usa diff`.
 */
function yamlKey(id: string): string {
  return `"${id.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n')}"`;
}

/** Extracts the machine-readable trailer from a previously rendered report. */
export function parseTrailer(markdown: string): string | null {
  // indexOf + slice rather than /BEGIN([\s\S]*?)END/: the wildcard form is
  // polynomial on input containing many partial BEGIN markers, and this runs
  // on documents supplied by whoever hands us a report.
  //
  // Find the END first and then walk back: a report that *quotes* an earlier
  // BEGIN marker (or one concatenated with a decoy) must still yield its own
  // trailer, so the nearest BEGIN before END is the one that matters.
  // Last END wins: in a concatenation of reports the newest trailer is the
  // one that matters. (First-END returned the oldest — stale diffs.)
  const end = markdown.lastIndexOf(TRAILER_END);
  if (end < 0) return null;
  const start = markdown.lastIndexOf(TRAILER_BEGIN, end);
  if (start < 0) return null;
  const body = markdown.slice(start + TRAILER_BEGIN.length, end);

  // Tolerate trailing spaces, CRLF line endings, and `yml` shorthand.
  const fence = /```ya?ml[ \t]*\r?\n/.exec(body);
  if (!fence) return null;
  const yamlStart = fence.index + fence[0].length;
  // Last fence wins: a hostile rule id can legally contain ``` inside its
  // quoted YAML string, so the first fence after the header is not
  // necessarily the closing one. The emitted closing fence is always last.
  const yamlEnd = body.lastIndexOf('```');
  return yamlEnd <= yamlStart ? body.slice(yamlStart) : body.slice(yamlStart, yamlEnd);
}
